### ISSUE TITLE
alveo u200 Bad URI regex_error

### ISSUE THREAD

**Issue by manwapri** [ubimust/ETHMiner-OpenCL-FPGA-Mining-OpenCL-Accelerators-Xilinx-Alveo-U200-Serie#2]
Procedure followed:
```
git clone https://github.com/ubimust/ETHMiner-OpenCL-FPGA-Mining-OpenCL-Accelerators-Xilinx-Alveo-U200-Serie.git
git submodule update --init --recursive
mkdir build
cd build
/home/software/cmake3.17/bin/cmake ..
/home/software/cmake3.17/bin/cmake --build .
make install
```

Getting below error while mining:
```
[manwapri@localhost build]$ /usr/local/bin/ethminer --pool stratum://0x6CdEDBc29xxxxxxx.nnnn:@asia1.ethermine.org:14444


ethminer 0.18.0-alpha.3
Build: linux/release/gnu

Error: Bad URI : regex_error
```

I have installed u200 with bitstream:
```
[manwapri@localhost build]$ lspci | tail -2
01:00.0 Processing accelerators: Xilinx Corporation Device 5000
01:00.1 Processing accelerators: Xilinx Corporation Device 5001
```

**Comment by manwapri** [comment]
enable devtool 6 and then download and install ethminer

scl enable devtoolset-6 bash

**Comment by NikolIT** [comment]
Hi.
I had a problem running the miner on the same equipment (alveo u200), namely the miner does not see the equipment. Can you help fix this error?
Thanks.

**Comment by manwapri** [comment]
Hi,

Regex error is because of compiler version you are using is less than 6,
you must use gcc version 7 or 7+.
It will solve your regex issue but still it will not detect alveo u200, it
requires code change, I am also working on it.
If you are a developer or you know any developer, get code change from them.

Update me if it will get resolved.


Regards,
Priyesh.

**Comment by NikolIT** [comment]
Thanks for the quick reply, I will let you know when it solves this problem.

нд, 21 лют. 2021, 20:25 користувач manwapri <notifications@github.com> пише:

> Hi,
>
> Regex error is because of compiler version you are using is less than 6,
> you must use gcc version 7 or 7+.
> It will solve your regex issue but still it will not detect alveo u200, it
> requires code change, I am also working on it.
> If you are a developer or you know any developer, get code change from
> them.
>
> Update me if it will get resolved.
>
>
> Regards,
> Priyesh.
>

**Comment by countDmone** [comment]
@NikolIT how are you progressing with the issues surrounding the bitstream and having your U200 card recognized? Any help you can offer me in getting this setup will be greatly appreciated. Thank you.
